name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make-build-dir
      run: mkdir build
    - name: cd-build-dir
      run: cd build
    - name: cmake-generate-makefile
      run: cmake ..
    - name: cmake-build
      run: cmake --buld ..
